/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.slide2;

import com.mycompany.slide2.demo.NewClassListQLNV;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author leanh
 */
public class ChangeNV extends javax.swing.JFrame {
private ArrayList<NewClassListQLNV> list = new ArrayList<>();
    /**
     * Creates new form AddNV
     */
    private ListNhanVien home;
    
    public ChangeNV(Frame parent, boolean modal) {
        
        initComponents();
        home = (ListNhanVien) parent;
        this.setLocationRelativeTo(null);
        this.setTitle("Sửa thông tin nhân viên");
    }

    private ChangeNV() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbDateTime = new javax.swing.JLabel();
        lbnumberphone = new javax.swing.JLabel();
        lbHeso = new javax.swing.JLabel();
        lbLuong = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TFName = new javax.swing.JTextField();
        TFDateTime = new javax.swing.JTextField();
        TFNumberPhone = new javax.swing.JTextField();
        TFHeSo = new javax.swing.JTextField();
        TFLuong = new javax.swing.JTextField();
        btEdit = new javax.swing.JButton();
        btCanel = new javax.swing.JButton();
        lbRoom = new javax.swing.JLabel();
        TFRoom = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Sửa Thông Tin Nhân Viên");

        lbName.setText("HỌ TÊN");

        lbDateTime.setText("NGÀY SINH");

        lbnumberphone.setText("SỐ ĐT");

        lbHeso.setText("HỆ SỐ");

        lbLuong.setText("LƯƠNG");

        btEdit.setText("Lưu");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btCanel.setText("Thoát");
        btCanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCanelActionPerformed(evt);
            }
        });

        lbRoom.setText("PHÒNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLuong)
                            .addComponent(lbHeso)
                            .addComponent(lbnumberphone)
                            .addComponent(lbDateTime)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbRoom)
                                .addComponent(lbName)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(btCanel))
                            .addComponent(TFName)
                            .addComponent(TFDateTime)
                            .addComponent(TFNumberPhone)
                            .addComponent(TFHeSo)
                            .addComponent(TFLuong)
                            .addComponent(TFRoom))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRoom)
                    .addComponent(TFRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDateTime))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFNumberPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFHeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbHeso))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbLuong))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btEdit)
                                    .addComponent(btCanel)))
                            .addComponent(lbnumberphone)))
                    .addComponent(lbName))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
//   
//        
        String Room ="", Name ="", DateTime ="";
        int NumberPhone = 0;
        float HeSo = 0, Luong = 0;
        boolean test = true;
        
        Room = TFRoom.getText();
        Name = TFName.getText();
        DateTime = TFDateTime.getText();
        
        
        try {
            NumberPhone = Integer.parseInt(TFNumberPhone.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "SĐT phải là số!");
            test = false;
        }
            
        try {
            HeSo = Float.parseFloat(TFHeSo.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Hệ số phải là số!");
            test = false;
        }
            
        try {
            Luong = Float.parseFloat(TFLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Lương phải là số!");
            test = false;
        }
        if(test) {
            NewClassListQLNV cl = new NewClassListQLNV(Room,Name,
                    DateTime, NumberPhone,HeSo,Luong );
            home.UpdateNV(cl);
            JOptionPane.showMessageDialog(this, 
                    "Cập nhật thành công!");
            this.dispose();
            
        }
//        
//       
//        
//        
//        
//        
    }//GEN-LAST:event_btEditActionPerformed

    private void btCanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCanelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFDateTime;
    private javax.swing.JTextField TFHeSo;
    private javax.swing.JTextField TFLuong;
    private javax.swing.JTextField TFName;
    private javax.swing.JTextField TFNumberPhone;
    private javax.swing.JTextField TFRoom;
    private javax.swing.JButton btCanel;
    private javax.swing.JButton btEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDateTime;
    private javax.swing.JLabel lbHeso;
    private javax.swing.JLabel lbLuong;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbRoom;
    private javax.swing.JLabel lbnumberphone;
    // End of variables declaration//GEN-END:variables

    public void setChangeData(NewClassListQLNV s) {
        TFRoom.setText(s.getNVID());
        TFRoom.setEditable(false);
        TFName.setText(s.getName());
        TFDateTime.setText(s.getDatetime());
        TFNumberPhone.setText(s.getNumberPhone() + "");
        TFHeSo.setText(s.getCoefficient() + "");
        TFLuong.setText(s.getSalary() + "");
        
    }

   

   
}
